<?php

namespace ContainerXjtPMnW;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_LAsACsjService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.lAsACsj' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.lAsACsj'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'manager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'recipe' => ['privates', '.errored..service_locator.lAsACsj.App\\Entity\\Recipe', NULL, 'Cannot autowire service ".service_locator.lAsACsj": it references class "App\\Entity\\Recipe" but no such service exists.'],
        ], [
            'manager' => '?',
            'recipe' => 'App\\Entity\\Recipe',
        ]);
    }
}
